version: "3.9"

services:
  db:
    image: postgres:15
    container_name: jandboard_db
    restart: always
    environment:
      POSTGRES_USER: jandson
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: jandboard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: jandboard_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jandboard.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
